"""Phase 5: TTM & Accessibility."""
from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

from qsot_v2.core.checks import PHASE_CHECKS
from qsot_v2.physics import (
    BACKGROUND_BUILDERS,
    MetricToChannelMap,
    QuantumState,
    compute_accessibility_score,
    compute_memory_kernel,
)

if TYPE_CHECKING:
    from qsot_v2.core.phase_context import PhaseContext


def run_phase5(ctx: PhaseContext) -> None:
    """Execute Phase 5 checks."""
    state0 = QuantumState.from_bloch(np.pi / 2, 0.0).rho  # |+>
    bg_flat = BACKGROUND_BUILDERS["flat"](10)
    bg_schwarz = BACKGROUND_BUILDERS["schwarzschild"](10)
    mapper = MetricToChannelMap(sensitivity=1.0)
    ch_identity = mapper.to_channel(bg_flat)
    ch_dephasing = mapper.to_channel(bg_schwarz, channel_type="dephasing")

    # --- TTM category 1: detector self-test on a SYNTHETIC injected backflow ---
    # The third state is state0 reappearing -- an artificial coherence revival the
    # configured channels do not produce. A PASS validates that the TTM detector
    # registers non-Markovian backflow; it is NOT evidence that the model exhibits
    # non-Markovian physics.
    synthetic_traj = [
        state0,
        ch_dephasing.apply(state0),
        state0,  # artificial coherence backflow (injected, not model-produced)
    ]
    synthetic_channels = [ch_dephasing, ch_identity]
    selftest = compute_memory_kernel(synthetic_traj, synthetic_channels, ricci_norm=0.0)
    selftest["source"] = "synthetic_injected_backflow"
    selftest["interpretation"] = (
        "Detector self-test: an artificial coherence backflow is injected to confirm "
        "the TTM registers nm > 0. Validates the detector only; not evidence that the "
        "model exhibits non-Markovian physics."
    )
    ctx.result.checks["memory_kernel_selftest_detects_injected_backflow"] = (
        "PASS" if selftest["nm_measure"] > 0.0 else "FAIL"
    )
    ctx.result.observations["memory_kernel"] = selftest

    # --- TTM category 2: the model's OWN trajectory (phenomenological output) ---
    # Generated by applying the configured channel consistently, with no injected
    # revival. The phenomenological map is Markovian by construction, so the model
    # trajectory exhibits no non-Markovian backflow (nm ~ 0).
    model_traj = [
        state0,
        ch_dephasing.apply(state0),
        ch_dephasing.apply(ch_dephasing.apply(state0)),
    ]
    model_channels = [ch_dephasing, ch_dephasing]
    model_mem = compute_memory_kernel(model_traj, model_channels, ricci_norm=0.0)
    model_mem["source"] = "model_generated_trajectory"
    model_mem["interpretation"] = (
        "The phenomenological channel map is Markovian by construction; the model's "
        "own trajectory exhibits no non-Markovian backflow (nm ~ 0)."
    )
    ctx.result.observations["memory_kernel_model_trajectory"] = model_mem

    # accessibility score checks
    score_pass = compute_accessibility_score(gate_report={"pass": True, "gate": "PASS"})
    score_fail = compute_accessibility_score(gate_report={"pass": False, "gate": "FAIL"})
    ctx.result.checks["accessibility_passes_fully"] = "PASS" if score_pass["final_access_score"] == 1.0 else "FAIL"
    ctx.result.checks["accessibility_fails_fully"] = "PASS" if score_fail["final_access_score"] == 0.0 else "FAIL"

    score_nm = compute_accessibility_score(
        gate_report={"pass": True, "gate": "PASS"},
        markov_report={"nm_measure": 0.5, "depth": 1},
    )
    ctx.result.checks["accessibility_penalizes_non_markovianity"] = (
        "PASS" if (score_nm["final_access_score"] < score_nm["base_score"] and score_nm["markov_penalty"] > 0.0) else "FAIL"
    )

    score_kd = compute_accessibility_score(
        gate_report={"pass": True, "gate": "PASS"},
        kd_metrics={"negativity_proxy": 0.01},
    )
    ctx.result.checks["accessibility_penalizes_kd_negativity"] = (
        "PASS" if (score_kd["final_access_score"] < score_kd["base_score"] and score_kd["kd_penalty"] > 0.0) else "FAIL"
    )

    ctx.result.observations["accessibility_scores"] = {
        "score_pass": score_pass,
        "score_fail": score_fail,
        "score_nm": score_nm,
        "score_kd": score_kd,
    }


def skip_phase5(ctx: PhaseContext) -> None:
    """Skip Phase 5 checks."""
    for c in PHASE_CHECKS["phase5_ttm_accessibility"]:
        ctx.result.checks[c] = "SKIPPED"
